server:
  port: 8088

#emp配置，面向对象
#emp:
#  lastName: zh
#  age: 24
#  salary: 10000
#  boss: true
#  birthday: 1995/04/07
#  map:
#    key1: value1
#    key2: value2
#  list:
#    - one
#    - two
#    - three
#  forte:
#    name: java
#    time: 1